#pragma once

namespace Synchronization {
	enum SynchronizationResult {
		SYNCHRONIZATION_OK,
		SYNCHRONIZATION_ERR_CANNOT_OPEN_PIPE,
		SYNCHRONIZATION_ERR_SEND_PING,
		SYNCHRONIZATION_ERR_RECV_PONG,
		SYNCHRONIZATION_ERR_INVALID_PONG,
		SYNCHRONIZATION_ERR_SEND_PID_REQUEST,
		SYNCHRONIZATION_ERR_RECV_PID_ANSWER,
		SYNCHRONIZATION_ERR_INVALID_RECV_PID,
		SYNCHRONIZATION_ERR_RECV_PID,
		SYNCHRONIZATION_ERR_OPEN_PROCESS,
		SYNCHRONIZATION_ERR_TERMINATE_PROCESS,
		SYNCHRONIZATION_ERR_WAIT_PROCESS
	};

	SynchronizationResult SynchronizeWithLauncher();
}